name: env-jp

channels:
  - conda-forge

dependencies:
  - python=3.9
  - pip

  # Data
  - pandas

  # pip requirements for git hosted package
  - pip:
      - wheel
      - buildtools
      - git+https://github.com/cinemagoer/cinemagoer
      - alive_progress
